name: gamedev_helpers_core
description: Core for gamedev_helpers that can be used serverside.
version: 2.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  dartemis: ^0.9.0
  vector_math: ^2.1.0

dev_dependencies:
  build_runner: ^2.1.5
  dartemis_builder: ^0.3.0
